#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PackDrop.Resource", IsApplication=true)]

namespace PackDrop
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Resource.String.ApplicationName = global::PackDrop.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Resource.String.Hello = global::PackDrop.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Continue = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int artworkPreview = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int downBtn = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int editText = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int gallery = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int game1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int game2 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int game3 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int game4 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int game5 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int game6 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int game7 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int game8 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int game9 = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int gameArea = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int gameLayout = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int introText = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int leftBtn = 2131099656;
			
			// aapt resource value: 0x7f060015
			public const int logoImage = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int mainLayout = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int rightBtn = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int scoreLbl = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ArtworkPreview = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GameOver = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int InGame = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int tap_anywhere = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
